refac: removes sign-and-upload from every specific distro and make it generic
Signed-off-by: Vitor Savian <vitor.savian@suse.com>

diff --git a/scripts/sign-and-upload b/scripts/sign-and-upload
--- a/scripts/sign-and-upload
+++ b/scripts/sign-and-upload
@@ -11,7 +11,7 @@ dnf install -y ca-certificates createrepo_c
 pip install --upgrade boto3 pexpect
 
 pushd $(dirname $0)/..
-. ./scripts/version
+. ../policy/centos9/scripts/version
 popd
 
 cat <<\EOF >~/.rpmmacros
@@ -27,9 +27,18 @@ if [ -z "$RPM_CHANNEL" ]; then
   exit 1
 fi
 
-TARGET_S3_PATH="rke2/$RPM_CHANNEL/common/slemicro/noarch"
-TARGET_SOURCE_S3_PATH="rke2/$RPM_CHANNEL/common/slemicro/source"
-TARGET_RPM_PATH="dist/centos9/noarch"
+if [ -z "$RPM_OS"]; then
+  echo "RPM_OS not defined, failing rpm upload"
+  exit 1
+fi
+
+if [ -z "$RPM_OS_S3_PATH"]; then
+  echo "RPM_OS_S3_PATH not defined, failing rpm upload"
+  exit 1
+fi
+
+TARGET_S3_PATH="rke2/$RPM_CHANNEL/common/$RPM_OS_S3_PATH/noarch"
+TARGET_SOURCE_S3_PATH="rke2/$RPM_CHANNEL/common/$RPM_OS_S3_PATH/source"
 
 case "$RPM_CHANNEL" in
 "testing")
@@ -85,5 +94,6 @@ wget https://raw.githubusercontent.com/rancher/ecm-distro-tools/master/bin/rpm_t
 chmod +x rpm_tooling
 mv ./rpm_tooling /usr/bin
 
-rpm_tooling --bucket $AWS_S3_BUCKET/$TARGET_S3_PATH --region us-east-1 --sign --sign-pass $PRIVATE_KEY_PASS_PHRASE --aws-access-key $AWS_ACCESS_KEY_ID --aws-secret-key $AWS_ACCESS_KEY_ID dist/slemicro/noarch/rke2-*.rpm
-rpm_tooling --bucket $AWS_S3_BUCKET/$TARGET_SOURCE_S3_PATH --region us-east-1 --sign --sign-pass $PRIVATE_KEY_PASS_PHRASE --aws-access-key $AWS_ACCESS_KEY_ID --aws-secret-key $AWS_ACCESS_KEY_ID dist/micro/source/rke2-*src.rpm
+rpm_tooling --bucket $AWS_S3_BUCKET/$TARGET_S3_PATH --region us-east-1 --sign --sign-pass $PRIVATE_KEY_PASS_PHRASE --aws-access-key $AWS_ACCESS_KEY_ID --aws-secret-key $AWS_ACCESS_KEY_ID dist/$RPM_OS/noarch/rke2-*.rpm
+rpm_tooling --bucket $AWS_S3_BUCKET/$TARGET_SOURCE_S3_PATH --region us-east-1 --sign --sign-pass $PRIVATE_KEY_PASS_PHRASE --aws-access-key $AWS_ACCESS_KEY_ID --aws-secret-key $AWS_ACCESS_KEY_ID dist/$RPM_OS/source/rke2-*src.rpm
+
